services:
  mysql:
    image: 'mysql:8.0'   # Version stable existante
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - '3306:3306'      # Format host:container
    volumes:
      - mysql_data:/var/lib/mysql  # Persistance des donn√©es

volumes:
  mysql_data:
